title: Shader Tutorials
theme: jekyll-theme-midnight
markdown: kramdown
github_username: Xibanya
twitter_username: ManuelaXibanya
url: "http://Xibanya.github.io"
baseurl: "/ShaderTutorials"
show_downloads: false

collections:
  tutorials:
    output: true
    sort_by: part
    permalink: /:collection/:name
