title: Shader Tutorials
theme: jekyll-theme-midnight
markdown: kramdown
url: "http://Xibanya.github.io"
baseurl: "/ShaderTutorials"
show_downloads: false

github_username: Xibanya
twitter_username: ManuelaXibanya
discord: https://discord.gg/79mD4R7
patreon: https://www.patreon.com/teamdogpit

collections:
  tutorials:
    output: true
    sort_by: part
    permalink: /:collection/:name
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
