title: Shader Tutorials
markdown: kramdown
url: "http://Xibanya.github.io"
baseurl: "/ShaderTutorials"
show_downloads: false

github_username: Xibanya
twitter_username: ManuelaXibanya
twitter: ManuelaXibanya
discord: 79mD4R7
patreon: teamdogpit

permalink: /:categories/:title:output_ext
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
