title: Shader Tutorials
theme: jekyll-theme-midnight
markdown: kramdown
github_username: Xibanya
url: "http://Xibanya.github.io"
baseurl: "/ShaderTutorials"

collections:
  tutorials:
    output: true
    sort_by: part
    permalink: /:collection/:name
    
defaults:
  -
    scope:
      path: "tutorial" # an empty string here means all files in the project
    values:
      layout: "post"
